### PR TITLE
rcd demosaic: speedup and reduced memory usage

### PR DESCRIPTION
**Pull request by heckflosse**
@butcherg @CarVac

Can you please test?

### CODE REVIEW

**Comment by butcherg** [comment]
I set up a special rawproc "test stand" for librtprocess, been meaning to do this for a while...

The rcd_speedup_new  branch is running ~0.4sec slower than master:

```
glenn@bena:~/ImageStuff/rawproc-librtprocess/rawproc/build-linux$ time src/img -f "DSG_3111.NEF:rawdata=crop" demosaic:rcd foo.jpg
configuration file: /home/glenn/.rawproc/rawproc.conf
number of input files to be processed: 1

1/1: Loading file DSG_3111.NEF rawdata=crop... done. (0.519273sec)
Image size: 4948x3280
demosaic: rcd (24 threads, 0.208562sec)
Saving file foo.jpg ... done. (0.050079sec)

1 file processed.

```


```
glenn@bena:~/ImageStuff/rawproc10/rawproc/build-linux$ time src/img -f "/home/glenn/Photography/rawproc/DSG_3111.NEF:rawdata=crop" demosaic:rcd foo.jpg
configuration file: /home/glenn/ImageStuff/rawproc10/rawproc/build-linux/src/rawproc.conf
number of input files to be processed: 1

1/1: Loading file /home/glenn/Photography/rawproc/DSG_3111.NEF rawdata=crop... done. (0.519238sec)
Image size: 4948x3280
demosaic: rcd (24 threads, 0.167909sec)
Saving file foo.jpg ... done. (0.054967sec)

1 file processed.

```

**Comment by heckflosse** [comment]
@butcherg Thanks for testing. I will investigate...

**Comment by heckflosse** [comment]
@butcherg On my really old 8-core AMD FX8350 I measure ~300 ms for a 8280 x 5512 raw... strange...

**Comment by butcherg** [comment]
@heckflosse , did I need to compile librtprocess with -fopenmp?

**Comment by heckflosse** [comment]
@butcherg openmp is enabled by default

**Comment by heckflosse** [comment]
I compared processing time of RT rcd with librtprocess rcd. RT version is 25% faster, but I don't know why...
Searching...

**Pull request merged**
