### PR TITLE
rcd_demosaic(): SSE code for step 3

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by heckflosse** [comment]
@CarVac Is there something wrong with the Travis CI configuration?

**Comment by heckflosse** [comment]
@butcherg Could you test this pr please?

**Comment by CarVac** [comment]
It appears the CI has been broken for some time; something about the initial git pull fails.

**Comment by CarVac** [comment]
In fact, I'm not sure it ever worked.

**Comment by butcherg** [comment]
I think I can do it some time this weekend...

**Comment by butcherg** [comment]
Static builds no longer available?

**Comment by heckflosse** [comment]
> Static builds no longer available?

???

**Comment by butcherg** [comment]
> > Static builds no longer available?
> 
> ???

I responded via email, but it hasn't shown up...

The switch I used last time, WITH_STATIC_LIB, flags "Manually-specified variables were not used by the project" in the cmake .. run.  Went to inspect the log, commit #3b57e7 appears to have removed the switch and the cmake script stuff behind it.

**Comment by CarVac** [comment]
Hmm, I'm not sure why @cryptomilk did that.

**Comment by cryptomilk** [comment]
https://cmake.org/cmake/help/v3.18/variable/BUILD_SHARED_LIBS.html

**Comment by butcherg** [comment]
Well, that works...  👍 Thanks, @cryptomilk !

Took me a year to learn the autotools, now I have to figure out cmake.  I'm creating a pull request to update the optional cmake directive.

**Comment by cryptomilk** [comment]
What do you mean exactly?

`cmake -L` or `ccmake` are listing it with a description :-)

**Comment by butcherg** [comment]
-L, didn't know that...

I learned autotools to configure rawproc; I haven't studied cmake yet to do that.  When I go to compile other software, I just learn enough to make it work; I have that "sense of the landscape" with autotools to know stuff not specifically documented, but I'm not there yet with cmake.

If we expect others to be able to compile our stuff out-of-the-box, we need to document all they need in our instructions; we can't assume they just know autotools or cmake...

**Comment by heckflosse** [comment]
@butcherg 
>If we expect others to be able to compile our stuff out-of-the-box, we need to document all they need in our instructions; we can't assume they just know autotools or cmake..

:+1:

**Pull request merged**
