### PR TITLE
Adapted the code to PhotoFlow needs

### PR DESCRIPTION
**Pull request by aferrero2707**
I have started to adapt the LibRTProcess code to the peculiar needs of PhotoFlow’s processing pipeline.

The good news is that it works, and that the inclusion of the LibRTProcess code was rather easy.
hence, if you plan to add more algorithms to the library I will be very happy!
The experimental code is in the [rtprocess branch](https://github.com/aferrero2707/PhotoFlow/tree/rtprocess).

LibRTProcess required some modifications in order to make it compatible with PhotoFlow.
Here is a short description of the changes:

- Array2D: I have introduced a special constructor that allows to create a pixel matrix that only contains a portion of the entire image, but that can be addressed as if the entire image was available (i.e. using row and column indexes from the top-left corner) This is obtained using some simple pointer arithmetics, however there are for the moment no checks to prevent out-of-bounds accesses.

- Amaze: I have modified the code such that the “winw” and “winh” parameters really represent the extents of a sub-portion of the entire image. I have the impression that this was also the original idea of the code, but as far as I understand the code should use the total width of the RAW  image, and not the width of the processed window, to handle the boundary conditions. I have tried to fix that in my version

- CA correction: like in the Amaze case, I need to have the possibility to apply the CA correction to a portion of the entire image, therefore I have introduced some winx/winy/winw/winh parameters like for the Amaze case. The total width and height of the RAW image is directly taken from the rawData object

- CA correction: I have temporarily disabled a couple of SSE2 optimisations at the end of the routine, just until I am sure I am handling the indexes correctly

Let me know what you think!

### CODE REVIEW

**Comment by heckflosse** [comment]
@aferrero2707 
I also temporarily disable SSE2 code if I search for bugs. But I do it in a different way which is much easier to search. 

Just replace `__SSE2__` by `__SSE299__`. No need to use comments and easy to find if you want to enable it again.

**Comment by CarVac** [comment]
What was wrong with the old implementation of CFA?

With this way, it seems I can't put it as a member variable of my image pipeline class and set the values upon loading the image.

**Comment by CarVac** [comment]
Would that require manual memory management @heckflosse? I'd like to avoid that.

**Comment by heckflosse** [comment]
@CarVac No, you can still pass an array2d<float> or use a similar class if the class has a

```
    // use as pointer to T**
    operator T**()
    {
        return ptr;
    }
```

**Comment by CarVac** [comment]
Can you give the CFA a default and copy constructor?

**Comment by CarVac** [comment]
Furthermore, that reintroduces an implicit dependence on LibRaw that I would prefer to avoid.

**Comment by heckflosse** [comment]
@aferrero2707 @CarVac The cfa pattern of a bayer sensor can be clearly defined be a 2x2 array. I really would like to use this simple pattern in the librtprocess interface. Convienence functions (for example to support dcraw/libraw filters) should be not part of the library imho.

**Comment by aferrero2707** [comment]
@CarVac @heckflosse 
I have no objections to keep the CFA interface simple, and move the code that imports the dcraw filters bitmask to somewhere else.

I will do the changes and update this pull request.

**Comment by aferrero2707** [comment]
@CarVac @heckflosse 
I restored the initial implementation of the ColorFilterArray object.

Could you please check if now it is fine?

**Comment by CarVac** [comment]
It seems to work just fine.

I haven't tested the correctness of your windowing changes, so that's up to you...

**Pull request merged**
