### PR TITLE
ported new raw ca correction code from rt, also exposed gaussian blur…

### PR DESCRIPTION
**Pull request by heckflosse**
… functionality

### CODE REVIEW

**Comment by heckflosse** [comment]
@aferrero2707 I merged upstream/master (which includes the changes of your pr) into my fork.
I tested ca_correction code (there were a lot of merge conflicts) in rt (where winx = 0 and winy = 0). Please test in your app as well.

**Comment by CarVac** [comment]
Array2d is usable with this interface, correct, since it exposes a float**?

I'd prefer that we leave the Array2d header in if users want to have it; otherwise they don't have to include it if they don't want to.

**Comment by heckflosse** [comment]
@CarVac 
> Array2d is usable with this interface, correct, since it exposes a float**?

yes

> I'd prefer that we leave the Array2d header in if users want to have it; otherwise they don't have to include it if they don't want to.

Keeping the array2d header which originates from rt likely will lead to conflicts if we (@aferrero2707 ;) change it. 

We may include a simple header (a modification of  the jaggedarray from rt) instead of array2d...

**Comment by heckflosse** [comment]
@CarVac Ok, not including the header would be fine.

**Comment by aferrero2707** [comment]
> I tested ca_correction code (there were a lot of merge conflicts) in rt (where winx = 0 and winy = 0). Please test in your app as well.

I will do the test in a couple of days.

**Comment by CarVac** [comment]
For me, *simple* means simple-to-use, which means avoiding manual memory management.

We can have the function signatures be `float**` still, very bare-bones.

But here's my use case:

Filmulator uses no manual memory management; it uses a wrapper class around `std::vector` for storing images. But this doesn't interface with the `float**`, so it needs some other class that exposes that.

I'd prefer if a super bare bones class that properly frees memory when it goes out of scope is bundled with librtprocess, to be used in situations like mine.

**Comment by heckflosse** [comment]
For me, simple means: simple to use: Pass some pointers to the processing and get back the proceseed stuff. Very imple approach...

**Comment by CarVac** [comment]
Yes please.

**Comment by heckflosse** [comment]
@CarVac done

**Comment by CarVac** [comment]
Now that I take a look at jaggedarray, it's just a bit too basic to be usable for Filmulator.

Can there be a default constructor and a resize method? It's fine if resize destroys the contents.

**Comment by heckflosse** [comment]
@CarVac Feel free to change jaggedarray for your needs or derive your own class from it:)

But please wait an hour or so with merge of pr. I still have some changes on hold

**Comment by CarVac** [comment]
I guess I'll try to add those functions myself before merging. I have a vague understanding of how to do it...

**Comment by heckflosse** [comment]
@CarVac I just pushed my latest changes.

**Comment by heckflosse** [comment]
@aferrero2707 I misunderstood the meaning of winh and winw I guess...

**Comment by aferrero2707** [comment]
@heckflosse the idea is to be able to process (for example demosaic) a small portion of the whole image. The input RAW data must be extended with respect of the `winx,winy,winw,winh` region to avoid any border processing for regions that are sufficiently inside the image.

In other words, the result of demosaicing a small portion of the RAW data should be exactly identical to an equivalent crop of the full demosaiced RAW image.

Hope this is more clear...

**Comment by heckflosse** [comment]
@aferrero2707 It's perfectly clear. But then we have to pass also raw_width and raw_height to the functions, or do I miss something?

**Comment by aferrero2707** [comment]
@heckflosse at this point, yes. Originally, the RAW dimensions were available from the `width` and `height` of the corresponding `array2D` (see for example [here](https://github.com/aferrero2707/librtprocess/blob/master/src/demosaic/amaze.cc#L58)).

**Comment by heckflosse** [comment]
@aferrero2707 Ok, I will add raw_width and raw_height now. Should be ready in a few minutes.

**Comment by heckflosse** [comment]
@aferrero2707 done

**Comment by aferrero2707** [comment]
On a side note, it is great to have an optimized gaussian blur implementation available in the library. I hope we will get even more general-purpose algorithm included as the development goes on!

My first wish would be a fast and optimized implementation of the bilateral blur operation. Frankly speaking, I find it as useful as the gaussian blur, and ir represents the basic building block of many high-quality filters (see for example [this article](http://people.csail.mit.edu/sparis/publi/2006/tr/Paris_06_Fast_Bilateral_Filter_MIT_TR.pdf) and the tone mapping filter implemented [here](http://people.csail.mit.edu/sparis/code/src/tone_mapping.tar.gz), which is at the basis of the recent *dynamic range compression* filter I implemented in PhF).

In the current [PhF code](https://github.com/aferrero2707/PhotoFlow/blob/stable/src/external/darktable/src/common/bilateral.c) I am using a bilateral blur implementation derived from Darktable, but I do not understand all the details of the algorithm, and I have the feeling one could optimize the code even further.

What do you think?

**Comment by heckflosse** [comment]
I also would appreciate a fast bilateral implementation to replace [the current one](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/bilateral2.h) in RT.

About the gaussian blur in RT:

1) Currently it's only optimized for SSE2. Hopefully we can add AVX/AVX512 code too.
2) It has some special cases which clearly need to be documented (for example the case where it uses iterated boxblur for very large sigma)

**Comment by heckflosse** [comment]
@CarVac @aferrero2707 

This may also be a candidate for librtprocess, at least it's used in RT and also in Luminance HDR

https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/rt_algo.cc#L59

**Pull request merged**
